root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main"
include_ext = ["go", "yaml", "sql"]
exclude_dir = ["tmp", "uploads"]
delay = 1000
stop_on_error = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
